### ISSUE TITLE
Version conflict on latest release v3.26.0 released yesterday, same version as 3.26.0 released 2 weeks ago

### ISSUE THREAD

**Issue by IvarNyga** [splunk/security_content#1560]
We installed from github 3.26.0 that was released two weeks ago. Yesterday a new 3.26.0 release has been issued with same version number but with updated content. Since version is the same I expect difficulties with upgrading. Could you please fix the version numbers?

**Comment by patel-bhavin** [comment]
Hello, IvarNyga! the previous release of 3.26.0 that occurred two weeks ago had some issues with SplunkBase approval process which is why we had to change the bits.

You can simply install the new version of 3.26.0 on your Splunk instance and it should upgrade just fine. Have you tried upgrading yet?

**Comment by IvarNyga** [comment]
Thanks, great!  Yes, upgraded just now and that went well.  But to avoid confusion I guess the version number _should_ have been bumped since the bits had changed. But no biggie of cource! Keep up the good work!
