### ISSUE TITLE
Saved searches still reference deprecated Cloud_Infrastructure Datamodel

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2254]
2 Saved Searches in ESCU (`default/savedsearches.conf`) still reference the `Cloud_Infrasturcture` datamodel which is no longer part of ESCU (it's been deprecated):

* ESCU - GCP GCR container uploaded - Rule
* ESCU - New container uploaded to AWS ECR - Rule

This causes some errors to be reported in the `_internal` logs.
![image](https://user-images.githubusercontent.com/58239192/174812048-6d428674-5fe1-47c6-a445-af07ba112273.png)

See also: [https://community.splunk.com/t5/Knowledge-Management/Data-model-Cloud-Infrastructure-was-not-found/m-p/541022](https://community.splunk.com/t5/Knowledge-Management/Data-model-Cloud-Infrastructure-was-not-found/m-p/541022)

**Comment by josehelps** [comment]
hey @ccl0utier unfortunately that datamodel was never shipped or part of ESCU and yes it has since been deprecated, for that matter of fact, one those detections have also been deprecated [1](https://github.com/splunk/security_content/blob/develop/detections/deprecated/gcp_gcr_container_uploaded.yml) and the other [2](new_container_uploaded_to_aws_ecr) is considered experimental (use at your own risk). We still include them as part of ESCU to avoid breaking any customers deployment whom might have enabled it. The original datamodel code was here https://github.com/splunk/cloud-datamodel-security-research.  I will discuss this with the team to see if there maybe an alternative to avoid these errors for users, maybe we do end up just yanking these out of security content. I will keep this open and come back with an answer, sorry I do not have better news :-/

**Comment by ccl0utier** [comment]
Sure @d1vious, thanks for the reply and no worries, just thought it was worth reporting it so users don't have to go through troubleshooting to find the root cause.

**Comment by josehelps** [comment]
Hey @ccl0utier this should be resolved in the next release 3.45.0 .. here is the PR https://github.com/splunk/security_content/pull/2294
