### ISSUE TITLE
Two different detection rules have same id

### ISSUE THREAD

**Issue by secnec** [splunk/security_content#2282]
These two detection rules have the same id: 2850c734-2d44-4431-8139-1a56f6f54c01

https://github.com/splunk/security_content/blob/develop/detections/web/web_jsp_request_via_url.yml

https://github.com/splunk/security_content/blob/develop/detections/web/spring4shell_payload_url_request.yml

**Comment by josehelps** [comment]
that should not be happening .. thank you for reporting it :-)

**Comment by pyth0n1c** [comment]
Thank you for the report @secnec !  We're taking two steps to fix this:

- First, we're updating the specific rules that you linked so that they don't have the same ID.
- Second, we're adding a check to our CI/CD pipeline to ensure that conflicts will throw an error.


Thanks!  I'll respond with the PR and fix in a bit.

**Comment by pyth0n1c** [comment]
We now have a PR open that fixes the original issue (duplicate IDs) and implements a check for duplicate IDs on commit to the repo via contentctl.py.  Of course, you can run contentctl locally, as well.  
We should have it merged shortly!

Please find the PR here:
https://github.com/splunk/security_content/pull/2286
