### ISSUE TITLE
App Manifest Version does not reflect release it was used in

### ISSUE THREAD

**Issue by pierewoehl** [splunk/security_content#2303]
https://github.com/splunk/security_content/blob/1e3d2076757b83033d2a44c1f8c4a976f95925f3/dist/escu/app.manifest#L8

ZIP is ok but tagged code does not reflect

**Comment by josehelps** [comment]
Hey @pierewoehl that is "as design" .. the artifacts under the dist folder are simply used and committed back into the repo for purely historical tracking purposes. The "true" version of content is the tag itself and the zip which is what gets uploaded to Splunk base. The effect you are reporting on is mainly due to CI/CD committing back the dist folder AFTER a release has been tagged which is why it does not match. See this portion of the CI job for more details. https://github.com/splunk/security_content/blob/develop/.github/workflows/build-and-validate.yml#L363-L379. In other words rely on the yamls on the tag and the zip file for the distrubted platform NOT what is on the `dist` folder. Hope this helps.

**Comment by josehelps** [comment]
I hope this explanation helped, going to close this out, but please feel free to re-open if you have any questions. @pierewoehl
