### ISSUE TITLE
Investigation Workbench Panels no longer on ESCU

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#2334]
The question came up on user slack, we introduced this on https://github.com/splunk/security_content/releases/tag/v3.0.1 .. but is no longer present in the latest version, might have not made it as part of the contentctl rewrite https://github.com/splunk/security_content/releases/tag/v3.37.0 ..

**Comment by P4T12ICK** [comment]
Workbench panels are still part of ESCU. But we don't ship workbench panel tabs (a group of workbench panels). I remember that we tried to create workbench panel tabs based on Analytics Story but the user experience was not great because then they had so many workbench panel tabs. In my opinion, we can keep it as it is and let the customer create their own workbench panel tabs from our workbench panels.
