### ISSUE TITLE
pytest failure

### ISSUE THREAD

**Issue by tccontre** [splunk/security_content#2354]
as requested by patrick, here is the issue for the pytest failure after submit detection PR for security content.

![Screenshot 2022-08-31 at 11 09 53](https://user-images.githubusercontent.com/26181693/187893811-e0e45adb-1e40-44b7-ac50-2857156f2fa6.png)

https://github.com/splunk/security_content/runs/8132008116?check_suite_focus=true

**Comment by pyth0n1c** [comment]
To provide a little more context, this is intended behavior at this time. In this example, the content failed validation due to an error in the yml (improperly calculated risk score).  You can see this if you scroll back in the logs some more:
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/87383215/187945848-a6f48cfc-95e6-4e44-b993-cc8ddad14503.png">
Having said that, it probably makes more sense to not have this function do a sys.exit(1) when it encounters an error. This function should either raise an exception that is caught by the caller or return a list of error(s) that can be caught by the caller and handled appropriately.
I will refactor this today and link the PR with the updates for review.
