### ISSUE TITLE
[BUG] Wrong Observables and potentially weird logic for Unknown Process Using The Kerberos Protocol 

### ISSUE THREAD

**Issue by DipsyTipsy** [splunk/security_content#2565]
### **Describe the bug**
The observable referenced in [Unknown Process Using The Kerberos Protocol](https://github.com/splunk/security_content/blob/develop/detections/endpoint/unknown_process_using_the_kerberos_protocol.yml) will never be a part of the search, as the fields are not a part of the tstats by or the table.

The logic for the join is also prone to mistakes as it only joins on the process_id, which has quite the chance of colliding in environments with multiple hosts.

### **Expected behavior**
I think the search requires a bit of a rewrite in order of doing what it's supposed to.

One way to go would be:
 - Change the search to join on process_id and an other field, like `dest`
 - Change the observable src_ip to dest ( referring to the host the Process is running on )
 - Add dest_ip to the subsearch, and be aware that dest and dest_ip is now referring to two different objects

### **App Version:**
 - ESCU: 3.61.0

**Comment by iso-rgomez** [comment]
The following rules are also using only process_id in a join, and are likely to cause this issue:

- Detect Outlook exe writing a zip file (renames process_id to malicious_id)
- GPUpdate with no Command Line Arguments with Network
- Outbound Network Connection from Java Using Default Ports
- SearchProtocolHost with no Command Line with Network
- Unknown Process Using The Kerberos Protocol
- Windows InstallUtil Unintall Option with Network
- Windows MSIExec With Network Connections

Beyond this, I've also observed a collision with process_guid in my environment, so it suffers from the same issue.  On Windows, guids are unique only within the context of the single host.  I'm not including Linux rules in this next list; I'm not sure how it's affected by this since I don't know how guids are handled over there. 
Here are the rules only joining on process_guid (some of these also use _time; I'm not sure how well that mitigates this, but host is probably a better choice):

- Active Setup Registry Autostart
- Add DefaultUser And Password in Registry
- Allow Inbound Traffic By Firewall Rule Registry
- Allow Operation with Consent Admin
- Auto Admin Logon Registry Entry
- Batch File Write to System32
- Detect Exchange Web Shell
- Disable AMSI Through Registry
- Disable Defender AntiVirus Registry
- Disable Defender BlockAtFirstSeen Feature
- Disable Defender Enhanced Notification
- Disable Defender MpEngine Registry
- Disable Defender Spynet Reporting
- Disable Defender Submit Samples Consent Feature
- Disable ETW Through Registry
- Disable Registry Tool
- Disable Security Logs Using MiniNt Registry
- Disable Show Hidden Files
- Disable UAC Remote Restriction
- Disable Windows App Hotkeys
- Disable Windows Behavior Monitoring
- Disable Windows SmartScreen Protection
- Disabling CMD Application
- Disabling ControlPanel
- Disabling Defender Services
- Disabling FolderOptions Windows Feature
- Disabling NoRun Windows App
- Disabling SystemRestore in Registry
- Disabling Task Manager
- ETW Registry Disabled
- Enabled RDP in Other Port Number
- Enable WDigest UseLoginCredential Registry
- Eventvwr UAC Bypass
- Hide User Account from Sign-In Screen
- Java Writing JSP File
- MS Exchange Mailbox Replication service writing Active Server Pages
- Malicious InProcServer32 Modification
- Monitor Registry Keys for Print Monitors
- Office Application Drop Executable
- Office Product Writing cab or inf
- Process Creating LNK file in Suspicious Location (renames process_guid to lnk_guid)
- Process Writing DynamicWrapperX
- Registry Keys Used For Privilege Escalation
- Registry Keys for Creating SHIM Databases
- Remcos client registry install entry
- Revil Registry Entry
- Sdclt UAC Bypass
- Set Default PowerShell Execution Policy To Unrestricted or Bypass
- SilentCleanup UAC Bypass
- Spoolsv Writing a DLL
- Suspicious Image Creation In Appdata Folder
- Suspicious WAV file in Appdata Folder
- Time Provider Persistence Registry
- WSReset UAC Bypass
- Windows Defacement Modify Transcodedwallpaper File (renames process_guid to proc_guid)
- Windows Defender Exclusion Registry Entry
- Windows Deleted Registry By A Non Critical Process File Path
- Windows Disable Change Password Through Registry
- Windows Disable Lock Workstation Feature Through Registry
- Windows Disable LogOff Button Through Registry
- Windows Disable Memory Crash Dump
- Windows Disable Notification Center
- Windows Disable Shutdown Button Through Registry
- Windows Disable Windows Group Policy Features Through Registry
- Windows Hide Notification Features Through Registry
- Windows InstallUtil Remote Network Connection
- Windows Modify Registry Qakbot Binary Data Registry
- Windows Modify Show Compress Color And Info Tip Registry
- Windows Registry Certificate Added
- Windows Registry Modification for Safe Mode Persistence
- Windows Service Creation Using Registry Entry

For an example of how this probably should be done, these rules include host in the join, which ensures that process_id will only uniquely be compared on the single system:

- DLLHost with no Command Line Arguments with Network
- Rundll32 with no Command Line Arguments with Network

**Comment by P4T12ICK** [comment]
Thank you for reporting it. We are already working on removing the joins for performance reasons.

**Comment by patel-bhavin** [comment]
Hello @DipsyTipsy : we have updated several detections to remove the joins!  https://github.com/splunk/security_content/releases/tag/v4.2.0.  Please feel free to open up a new issue for other searches that still have joins are not working as expected! Thank you so much for reporting it
