### ISSUE TITLE
[BUG] windows_lateral_tool_transfer_remcom.yml might be mapped to the wrong mitre technique

### ISSUE THREAD

**Issue by hRun** [splunk/security_content#3234]
### **Describe the bug**
the detection [https://github.com/splunk/security_content/blob/develop/detections/endpoint/windows_lateral_tool_transfer_remcom.yml ](url) is mapped to mitre technique t1570 lateral tool transfer. however the referenced attack data [https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1570/remcom/remcom_windows-sysmon.log](url) shows execution of the atomic test for t1569.002.
furthermore, while the detection could potentially catch lateral tool transfer depending on the commands executed with remcom.exe it does not do so explicitly. what it certainly catches is remote command execution with remcom though.

### **Expected behavior**
detection should be mapped to the correct mitre technique, name should look accordingly.

### **App Version:**
n/a

### **Additional context**
let me know what your opinion on this topic is and whether i should create a pr.

**Comment by patel-bhavin** [comment]
hello @hRun : thank you for raising this issue. I will update the mitre id to T1569.002(https://www.atomicredteam.io/atomic-red-team/atomics/T1569.002)  and also update the data source link! 

Also, due to limitations with splunkd, unfortunately, we cannot change the name of the search after we have shipped a detection. We will have to deprecate this detection and ship one with a new name! Will keep you posted!

**Comment by patel-bhavin** [comment]
Hello @hRun : we have updated the mitre ID and the detection name . 

https://github.com/splunk/security_content/pull/3235/files
